# -*- coding: utf-8 -*-
#
# Copyright (C) 2021 Storm Project.
#
# storm-ws is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

version: "2.2"
services:
    app:
        build:
            context: ./
            args:
                - ENVIRONMENT=DEV
        image: storm-ws
        restart: "unless-stopped"
        environment:
            - "REANA_SERVER_URL=reana-server-url-here"
            - "RATELIMIT_STORAGE_URL=redis://cache:6379/3"
            - "INVENIO_CACHE_TYPE=redis"
            - "INVENIO_WSGI_PROXIES=2"
            - "INVENIO_RATELIMIT_STORAGE_URL=redis://cache:6379/3"
            - "INVENIO_SEARCH_ELASTIC_HOSTS=['elasticsearch:9200']"
            - "INVENIO_CACHE_REDIS_URL=redis://cache:6379/0"
            - "INVENIO_CELERY_RESULT_BACKEND=redis://cache:6379/2"
            - "INVENIO_BROKER_URL=amqp://guest:guest@rabbitmq:5672/"
            - "INVENIO_CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672/"
            - "INVENIO_SQLALCHEMY_DATABASE_URI=postgresql+psycopg2://storm:storm@database/storm-db"

    cache:
        image: redis
        restart: "unless-stopped"
        read_only: true
        ports:
            - "6379:6379"

    rabbitmq:
        image: rabbitmq:3.8-management
        restart: "unless-stopped"
        ports:
            - "15672:15672"
            - "5672:5672"

    database:
        image: postgres:12.4
        restart: "unless-stopped"
        environment:
            - "POSTGRES_USER=storm"
            - "POSTGRES_DB=storm-db"
            - "POSTGRES_PASSWORD=storm"
        ports:
            - "5432:5432"

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
        restart: "unless-stopped"
        environment:
            - bootstrap.memory_lock=true
            - discovery.type=single-node
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        healthcheck:
            test: [ "CMD", "curl", "-f", "localhost:9200/_cluster/health?wait_for_status=green" ]
            interval: 30s
            timeout: 30s
            retries: 5
        ulimits:
            memlock:
                soft: -1
                hard: -1
        mem_limit: 1g
        ports:
            - "9200:9200"
            - "9300:9300"

    kibana:
        image: docker.elastic.co/kibana/kibana-oss:7.10.2
        environment:
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
            - "ELASTICSEARCH_HOSTS=http://elasticsearch:9200"
        ports:
            - "5601:5601"

    nginx:
        build: ./docker/nginx/
        image: storm-ws-nginx
        restart: "unless-stopped"
        ports:
            - "80"
            - "443"
