#
# This file is part of Brazil Data Cube Reproducible Research Management Server.
# Copyright (C) 2021 INPE.
#
# Brazil Data Cube Reproducible Research Management Server is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.
#
version: '2.2'
services:
    app:
        build:
            context: ./
            args:
                - ENVIRONMENT=DEV
        image: bdcrrm-server
        restart: "unless-stopped"
        environment:
            - "INVENIO_BROKER_URL=amqp://guest:guest@mq:5672/"
            - "INVENIO_CACHE_TYPE=redis"
            - "INVENIO_CACHE_REDIS_URL=redis://cache:6379/0"
            - "INVENIO_CELERY_RESULT_BACKEND=redis://cache:6379/2"
            - "INVENIO_CELERY_BROKER_URL=amqp://guest:guest@mq:5672/"
            - "RATELIMIT_STORAGE_URL=redis://cache:6379/3"
            - "SQLALCHEMY_DATABASE_URI=postgresql+psycopg2://geo-knowledge-hub:geo-knowledge-hub@db/geo-knowledge-hub"
    cache:
        image: redis
        restart: "unless-stopped"
        read_only: true
        ports:
            - "6379:6379"
    mq:
        image: rabbitmq:3.8-management
        restart: "unless-stopped"
        ports:
            - "15672:15672"
            - "5672:5672"
    db:
        image: postgres:12.4
        restart: "unless-stopped"
        environment:
            - "POSTGRES_USER=bdcrrm-server"
            - "POSTGRES_PASSWORD=bdcrrm-server"
            - "POSTGRES_DB=bdcrrm-server"
        ports:
            - "35432:5432"
