#
# This file is part of Brazil Data Cube Reproducible Research Management Server.
# Copyright (C) 2021 INPE.
#
# Brazil Data Cube Reproducible Research Management Server is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.
#
version: '2.2'
services:
    cache:
        extends:
            file: docker-services.yml
            service: cache
    rabbitmq:
        extends:
            file: docker-services.yml
            service: rabbitmq
    database:
        extends:
            file: docker-services.yml
            service: database
