# -*- coding: utf-8 -*-
#
# Copyright (C) 2021 Storm Project.
#
# storm-ws is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

version: "2.2"
services:
    cache:
        extends:
            file: docker-services.yml
            service: cache

    rabbitmq:
        extends:
            file: docker-services.yml
            service: rabbitmq

    database:
        extends:
            file: docker-services.yml
            service: database

    elasticsearch:
        extends:
            file: docker-services.yml
            service: elasticsearch

    kibana:
        extends:
            file: docker-services.yml
            service: kibana
