# -*- coding: utf-8 -*-
#
# Copyright (C) 2021 Storm Project.
#
# storm-ws is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

version: "2.2"
services:
    cache:
        extends:
            file: docker-services.yml
            service: cache

    rabbitmq:
        extends:
            file: docker-services.yml
            service: rabbitmq

    database:
        extends:
            file: docker-services.yml
            service: database

    elasticsearch:
        extends:
            file: docker-services.yml
            service: elasticsearch

    kibana:
        extends:
            file: docker-services.yml
            service: kibana

    worker:
        extends:
            file: docker-services.yml
            service: app
        restart: "always"
        command: [ "celery -A invenio_app.celery worker --loglevel=INFO" ]
        image: storm-ws
        depends_on:
            elasticsearch:
                condition: service_started
            cache:
                condition: service_started
            database:
                condition: service_started
            rabbitmq:
                condition: service_started

    web-api:
        extends:
            file: docker-services.yml
            service: app
        command: [ "uwsgi /opt/invenio/var/instance/uwsgi_rest.ini" ]
        image: storm-ws
        ports:
            - "5000"
        volumes:
            - uploaded_data:/opt/invenio/var/instance/data
            - archived_data:/opt/invenio/var/instance/archive

    nginx:
        extends:
            file: docker-services.yml
            service: nginx
        volumes:
            - static_data:/opt/invenio/var/instance/static
        depends_on:
            - web-api
        ports:
            - "80:80"
            - "443:443"

volumes:
    static_data:
    uploaded_data:
    archived_data:
