#
# This file is part of SpatioTemporal Open Research Manager Web Service.
# Copyright (C) 2021 INPE.
#
# SpatioTemporal Open Research Manager Web Service is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.
#
version: "2.2"
services:
    cache:
        extends:
            file: docker-services.yml
            service: cache

    rabbitmq:
        extends:
            file: docker-services.yml
            service: rabbitmq

    database:
        extends:
            file: docker-services.yml
            service: database

    elasticsearch:
        extends:
            file: docker-services.yml
            service: elasticsearch

    kibana:
        extends:
            file: docker-services.yml
            service: kibana

    # Worker
    worker:
        extends:
            file: docker-services.yml
            service: app
        restart: "always"
        command: [ "celery -A invenio_app.celery worker --loglevel=INFO" ]
        image: storm-ws
        depends_on:
            elasticsearch:
                condition: service_started
            cache:
                condition: service_started
            database:
                condition: service_started
            rabbitmq:
                condition: service_started
